spring:
  application:
    name: kafka
  cloud:
    config:
      server:
        git:
          uri: File://D:/jee-2020-06/workspace/spring-cloud-configserver/config
          basedir: /:\Users/kafka/AppData/Local/Temp/aaaaa
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
management:
  endpoints:
    web:
      expose: "*"